#!/bin/sh
mvn clean package && docker build -t muzammilnagariya/EDSApp .
docker rm -f EDSApp 2>/dev/null || true && docker run -it --name EDSApp -p 8080:8080 -p 4848:4848 -p 8181:8181 --name EDSApp muzammilnagariya/EDSApp
